services:
  server:
    image: golang:1.22.1-alpine3.19
    container_name: server
    tty: true
    volumes:
      - ./src/server:/code
    working_dir: /code
    ports:
      - '8000:8000'
    networks:
      - docker-network
    depends_on:
      mariadb:
        condition: service_healthy
  mariadb:
    image: mariadb:11.4.1-rc-jammy
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - docker-network
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      TZ: 'Asia/Tokyo'
    healthcheck:
      test: mariadb-check --databases $MARIADB_DATABASE -u $MARIADB_USER -p$MARIADB_PASSWORD
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - docker-network
networks:
  docker-network:
    driver: bridge