openapi: '3.0.2'
info:
  title: 42Activity API
  description: "アクティビティを管理するAPIです"
  version: '1.0'
servers:
  - url: http://localhost:4242
paths:
  /shifts:
    get:
      tags:
        - シフト管理
      summary: "シフトの取得"
      description: |
        ## 概要
        指定した日付のシフトを担当するUserの配列を返却する  
        指定した日付にシフトが存在しない場合は空の配列を返却する
      parameters:
        - name: date
          in: query
          required: false
          description: "絞り込む日付、未指定の場合は現在の日付"
          schema: {type: string, example: "2024-05-01"}
      responses:
        '200':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/shiftsArray'
        '400':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error400'
        '500':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error500'
    post:
      tags:
        - シフト管理
      summary: "シフトの追加"
      description: |
        ## 概要
        日付とそれに対応した複数loginで構成されるシフト配列をDBに反映する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './openapi.yml#/components/schemas/addShiftsRequestBody'
              required:
                - shift
      responses:
        '200':
          description: "追加した日付の配列を返却する"
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/addShiftsResponse'
        '400':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error400'
        '404':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error404'
        '500':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error500'
    delete:
      tags:
        - シフト管理
      summary: "シフトの削除"
      description: |
        ## 概要
        日付とそれに対応したloginのシフトを論理削除する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './openapi.yml#/components/schemas/deleteShiftsRequestBody'
              required:
                - login
                - date
      responses:
        '200':
          description: "削除したシフトを返却する"
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Shift'
        '400':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error400'
        '404':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error404'
        '500':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error500'
  /shifts/exchange:
    post:
      tags:
        - シフト管理
      summary: "シフトの交換"
      description: |
        ## 概要
        特定のシフトの担当者を交換する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './openapi.yml#/components/schemas/exchangeShiftsRequestBody'
              required:
                - login1
                - login2
                - date1
                - date2
      responses:
        '200':
          description: "交換後の交換対象者のシフトを返却する"
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/shiftsArray'
        '400':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error400'
        '404':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error404'
        '500':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error500'
  /users:
    post:
      tags:
        - ユーザ管理
      summary: "ユーザの追加"
      description: |
        ## 概要
        複数人のユーザの追加/更新を行う
        ## 注意点
        処理中にエラーが発生した場合、ロールバックは行われない  
        DBにすでに存在し、情報の更新がないユーザはスキップされる
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './openapi.yml#/components/schemas/usersArray'
              required:
                - users
      responses:
        '200':
          description: "追加/更新したuserの配列を返却する"
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/usersArray'
        '400':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error400'
        '500':
          description: |
            エラーメッセージと追加/更新に成功したuserの配列を返却する
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: {type: string, example: "Internal Server Error."}
                  users: {type: array, example: ["a", "b", "c"]}
    put:
      tags:
        - ユーザ管理
      summary: "ユーザの編集"
      description: |
        ## 概要
        intra名に紐づくuidとwalletアドレスを更新する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './openapi.yml#/components/schemas/UserData'
              required:
                - login
      responses:
        '200':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/UserData'
        '400':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error400'
        '404':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error404'
        '500':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error500'
  /activities:
    post:
      tags:
        - アクティビティ管理
      summary: "アクティビティの追加"
      description: |
        ## 概要
        42学生のアクティビティ(掃除など)を追加する  
        主にNFCタグを読み取った際にM5Stickが実行する
      requestBody:
        required: true
        description: |
          mac: M5Stickのmacアドレス  
          uid: 42学生を識別するuid
        content:
          application/json:
            schema:
              $ref: './openapi.yml#/components/schemas/ActivityData'
              required:
                - mac
                - uid
      responses:
        '200':
          description: "使用したuidとmacアドレスを返却する"
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/ActivityData'
        '400':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error400'
        '404':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error404'
        '500':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error500'
  /activities/cleanings:
    get:
      tags:
        - アクティビティ管理
      summary: "掃除アクティビティの取得"
      description: |
        ## 概要
        指定した期間で、M5Stickのroleがcleaningのアクティビティを返却する  
        期間の指定を行わない場合、現在の日付の午前0時から24時間分のデータを返却する
      parameters:
        - name: start
          in: query
          required: false
          description: |
            絞り込む期間の開始時刻(Unix秒)  
            未指定の場合は現在の日付の午前0時に設定される
          schema: {type: string, example: '1711966578', default: '1711897200'}
        - name: end
          in: query
          required: false
          description: |
            絞り込む期間の終了時刻(Unix秒)  
            未指定の場合はstart+24時間に設定される
          schema: {type: string, example: '1713176178', default: '1711983600'}
      responses:
        '200':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/cleaningsData'
        '400':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error400'
        '404':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error404'
        '500':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error500'
  /roles:
    post:
      tags:
        - ロール管理
      summary: "ロールの追加"
      description: |
        ## 概要
        M5Stickの役割を識別するroleを追加する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './openapi.yml#/components/schemas/RoleData'
              required:
                - name
      responses:
        '200':
          description: "追加したroleを返却する"
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/RoleData'
        '409':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error409'
        '500':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error500'
  /locations:
    post:
      tags:
        - ロケーション管理
      summary: "場所の追加"
      description: |
        ## 概要
        M5Stickの設置場所を追加する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './openapi.yml#/components/schemas/LocationData'
              required:
                - name
      responses:
        '200':
          description: "追加した設置場所を返却する"
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/LocationData'
        '409':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error409'
        '500':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error500'
  /m5sticks:
    post:
      tags:
        - M5Stick端末管理
      summary: "M5Stickの追加"
      description: |
        ## 概要
        M5Stickのmacアドレス、role、locationを追加する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './openapi.yml#/components/schemas/M5StickData'
              required:
                - mac
                - role
                - location
      responses:
        '200':
          description: "追加したM5Stickのデータを返却する"
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/M5StickData'
        '400':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error400'
        '404':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error404'
        '409':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error409'
        '500':
          description: ""
          content:
            application/json:
              schema:
                $ref: './openapi.yml#/components/schemas/Error500'
components:
  schemas:
    shiftsArray:
      type: array
      items:
        type: object
        properties:
            shifts:
              $ref: './openapi.yml#/components/schemas/Shift'
    addShiftsRequestBody:
      type: array
      items:
        type: object
        properties:
          date:
            type: string
            format: date
            example: "2024-05-01"
          login:
            type: array
            items:
              type: string
            example: ["user1", "user2"]
      example:
        - date: "2024-05-01"
          login: ["user1", "user2"]
        - date: "2024-05-02"
          login: ["user3", "user4"]
    exchangeShiftsRequestBody:
      type: object
      properties:
        login1:
          type: string
          example: "login1"
        login2:
          type: string
          example: "login2"
        date1:
          type: string
          example: "YYYY-MM-DD"
        date2:
          type: string
          example: "YYYY-MM-DD"
    deleteShiftsRequestBody:
      type: object
      properties:
        login:
          type: string
          example: "foo"
        date:
          type: string
          example: "YYYY-MM-DD"
    usersArray:
      type: object
      properties:
        users: 
          type: array
          items: 
            $ref: './openapi.yml#/components/schemas/UserData'
    addShiftsResponse:
      type: object
      properties:
        date: {type: array, example: ["2024-05-01", "2024-05-02"]}
    ActivityData:
      type: object
      properties:
        mac: {type: string, example: "00:00:00:00:00:00"}
        uid: {type: string, example: "foo"}
    cleaningsData:
      type: array
      items:
        type: object
        properties:
          ID: {type: integer, example: 1}
          UserID: {type: integer, example: 1}
          User:
            $ref: './openapi.yml#/components/schemas/User'
          M5StickID: {type: integer, example: 1}
          M5Stick:
            $ref: './openapi.yml#/components/schemas/M5Stick'
          CreatedAt: {type: integer, example: 1712666900}
    User:
      type: object
      properties:
        ID: {type: integer, example: 1}
        UID: {type: string, example: "var"}
        Login: {type: string, example: "foo"}
        Wallet: {type: string, example: "0xA0D9F5854A77D4906906BCEDAAEBB3A39D61165A"}
    Shift:
      type: object
      properties:
        ID: {type: integer, example: 1}
        Date: {type: string, example: "2024-05-01"}
        UserID: {type: integer, example: 1}
        User:
          $ref: './openapi.yml#/components/schemas/User'
        DeletedAt: {type: string, example: "2024-06-19T11:55:03.892Z"}
    M5Stick:
      type: object
      properties:
        ID: {type: integer, example: 1}
        Mac: {type: string, example: "00:00:00:00:00:00"}
        RoleId: {type: integer, example: 1}
        Role:
          $ref: './openapi.yml#/components/schemas/Role'
        LocationId: {type: integer, example: 1}
        Location:
          $ref: './openapi.yml#/components/schemas/Location'
    Role:
      type: object
      properties:
        ID: {type: integer, example: 1}
        Name: {type: string, example: "Cleaning"}
    Location:
      type: object
      properties:
        ID: {type: integer, example: 1}
        Name: {type: string, example: "F1"}
    UserData:
      type: object
      properties:
        login: {type: string, example: "foo", description: "intra名"}
        uid: {type: string, example: "var", description: "intra名に紐づくuid"}
        wallet: {type: string, example: "0xA0D9F5854A77D4906906BCEDAAEBB3A39D61165A", description: "walletアドレス"}
    RoleData:
      type: object
      properties:
        name: {type: string, example: "Cleaning"}
    LocationData:
      type: object
      properties:
        name: {type: string, example: "F1"}
    M5StickData:
      type: object
      properties:
        mac: {type: string, example: "00:00:00:00:00:00"}
        role: {type: string, example: "Cleaning"}
        location: {type: string, example: "F1"}
    Error400:
      type: object
      properties:
        error: {type: string, example: "Bad Request."}
    Error404:
      type: object
      properties:
        error: {type: string, example: "Not Found."}
    Error409:
      type: object
      properties:
        error: {type: string, example: "Conflict."}
    Error500:
      type: object
      properties:
        error: {type: string, example: "Internal Server Error."}
