openapi: '3.0.2'
info:
  title: 42Activity API
  description: "アクティビティを管理するAPIです"
  version: '1.0'
servers:
  - url: http://localhost:8000
paths:
  /activities:
    post:
      summary: "アクティビティの追加"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActivityData'
      responses:
        '200':
          description: "成功。uidとmacをjsonで返します"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActivityData'
        '400':
          description: "失敗。エラーメッセージをjsonで返します"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /activities/cleanings:
    get:
      summary: "掃除データの取得"
      description: "指定した期間でrole(cleaning)に紐づくデータを返します"
      parameters:
        - name: start
          in: query
          required: true
          description: "絞り込む期間の開始時刻(Unix秒)"
          schema: {type: string, example: '1711966578'}
        - name: end
          in: query
          required: true
          description: "絞り込む期間の終了時刻(Unix秒)"
          schema: {type: string, example: '1713176178'}
      responses:
        '200':
          description: "成功。掃除データをjsonで返します"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cleaningsData'
        '400':
          description: "失敗。エラーメッセージをjsonで返します"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    ActivityData:
      type: object
      properties:
        mac: {type: string, example: "00:00:00:00:00:00"}
        uid: {type: string, example: "foo"}
    cleaningsData:
      type: array
      items:
        type: object
        properties:
          ID: {type: integer, example: 1}
          UserID: {type: integer, example: 1}
          User:
            $ref: '#/components/schemas/User'
          M5StickID: {type: integer, example: 1}
          M5Stick:
            $ref: '#/components/schemas/M5Stick'
          CreatedAt: {type: integer, example: 1712666900}
    User:
      type: object
      properties:
        ID: {type: integer, example: 1}
        UID: {type: string, example: "foo"}
        Login: {type: string, example: "kakiba"}
    M5Stick:
      type: object
      properties:
        ID: {type: integer, example: 1}
        Mac: {type: string, example: "00:00:00:00:00:00"}
        RoleId: {type: integer, example: 1}
        Role:
          $ref: '#/components/schemas/Role'
        LocationId: {type: integer, example: 1}
        Location:
          $ref: '#/components/schemas/Location'
    Role:
      type: object
      properties:
        ID: {type: integer, example: 1}
        Name: {type: string, example: "Cleaning"}
    Location:
      type: object
      properties:
        ID: {type: integer, example: 1}
        Name: {type: string, example: "F1"}
    Error:
      type: object
      properties:
        error: {type: string, example: "Error message"}