# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

defaults:
  run:
    shell: bash
    working-directory: ../../

jobs:
  build:
    defaults:
      run:
        working-directory: ../../
    runs-on: ubuntu-latest
    env:
      MARIA_ROOT_PASS: mariadb-root-password"
      MARIA_NAME: mariadb-database"
      MARIA_USER: mariadb-user"
      MARIA_PASS: mariadb-password"
      MARIA_PORT: 3306"
      DSN: ${MARIA_USER}:${MARIA_PASS}@tcp(mariadb:${MARIA_PORT})/${MARIA_NAME}?parseTime=true"
      UID: uid"
      SECRET: secret"
      CALLBACK_URL: callback_url"
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.1"
      - name: Build
        run: go build ./cmd/ft_activity_api
      - name: Prepare test
        run: sudo apt install build-essential && export CGO_ENABLED=1
      - name: Test
        run: go test ./cmd/ft_activity_api
